WebApp/models.py
from . import db 
from flask_login import UserMixin


class PatientMoreDetail(db.Model) :
    id = db.Column(db.Integer, primary_key=True)
    blood_grp = db.Column(db.String(10))
    gender = db.Column(db.String(10))
    dob = db.Column(db.String(10))
    diseases_symptoms = db.Column(db.String(500))
    surgries = db.Column(db.String(500))
    sensitivities = db.Column(db.String(500))
    radiograph_test = db.Column(db.String(500))
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'))

class Patient(db.Model, UserMixin) :
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(200),unique=True)
    password = db.Column(db.String(200))
    first_name = db.Column(db.String(200))
    patient_more_detail =  db.relationship('PatientMoreDetail')

WebApp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

#Creating database
db = SQLAlchemy()
DB_NAME = "telemedicine_database.db"
 
def create_app() :
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "q1w2e3r4t5y6u7i8o9"
    #store database file
    app.config['SQLALCHEMY_DATABASE_URI'] =f'sqlite:///{DB_NAME}'
    #Inititlize DATAbase
    db.init_app(app)
    

    from .views import views
    from .auth import auth
    app.register_blueprint(views, url_prefix ='/')
    app.register_blueprint(auth, url_prefix ='/')
    
    from .models import Patient, PatientMoreDetail
    #create Datebase Object
    with app.app_context():
        db.create_all()
        
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader    
    def load_user(id) :
        return  Patient.query.get(int(id))
    
    return app     

# def create_database(app) :
#     if not path.exists('WebApp/' + DB_NAME) :
#         db.create_all(app=app)
#         print('Created DataBase!')

WebApp/auth.py
from flask import Blueprint,render_template,url_for,request,flash,redirect,url_for
from .models import Patient,PatientMoreDetail
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
auth = Blueprint('auth', __name__)

@auth.route('/login', methods = ['GET','POST'])
def login() :
    if request.method == 'POST' :
        email = request.form.get('email')
        password = request.form.get('password')

        patient = Patient.query.filter_by(email=email).first()
        if patient :
            if check_password_hash(patient.password, password) :
                flash('Logged in successfully!' ,category='success')
                login_user(patient, remember=True)
                return redirect(url_for('views.home'))
            else :
                flash('Incorrect passsword!! Try again.', category='error')

        else :
            flash('Email dosnt exist!', category='error')            
            
            
        
    return render_template('login.html' , patient=current_user)


@auth.route('/logout')
@login_required
def logout() :
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods = ['GET','POST'])
def register() :
    if request.method == 'POST' :
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        patient = Patient.query.filter_by(email=email).first()
        if patient :
            flash('Email already exists!', category='error')

        elif len(email) < 4 :
            flash('Email must be greater than 3 character!', category='error')
        elif len(firstName) < 3 :
            flash('First Name must be greater than 2 character!', category='error')
        elif password1 != password2 :
            flash('Password dosnt Match!', category='error')
        elif len(password1) < 7 :
            flash('password must be greater than 6 character', category='error')
        else :
            new_patient = Patient(email = email, first_name = firstName, password=generate_password_hash(password1,method='sha256'))
            db.session.add(new_patient)
            db.session.commit()
            login_user(new_patient, remember=True)
            flash('Account Created!!', category='success')
            return redirect(url_for('views.home'))
    else :
        pass

    return render_template('sign_up.html' , patient=current_user)   

WebApp/views.py
from flask import Blueprint, render_template
from flask_login import login_required,current_user

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home() :
    return render_template('home.html', patient = current_user)

WebApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
     rel="stylesheet"integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
     crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
     <link rel="stylesheet" href="{{ url_for('static', filename='css/signUp.css')}}">
     <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
    <title>{% block title %} {% endblock %}</title> 
</head>
<body>
    <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-danger p-4">
            {% if patient.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
              <a class="nav-item nav-link" id="register" href="/register">Resister</a>
              <a class="nav-item nav-link" id="login" href="/login">Login</a>
            {% endif %}
           
        </div>
      </div>
      <nav class="navbar navbar-dark bg-danger">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <h5>Web based wireless Remote monitering</h5>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories = true) %}
       {% if  messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
            {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
            {% endif %}
            {% endfor %}
       {% endif %}
      {% endwith %}
      <div class="container">
        {% block content %} {% endblock %}
      </div>
      <footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: #D80F08;">
    © 2022 Copyright: Ashutosh NITH
    <a class="text-dark" href="https://nith.ac.in/">NIT Hamirpur</a>
  </div>
  <!-- Copyright -->
</footer>
 




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
     integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" 
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" 
    crossorigin="anonymous"></script>
    
</body>
</html>

WebApp/templates/home.html
{% extends "base.html" %}
<title>{% block title %} Home {% endblock %}</title> 

{% block content %}

  <img src="{{ url_for('static', filename='images/telehealth-main.jpg')}}" alt="Loading Image" width="100%" height="100%">
 {% endblock %}

WebApp/templates/login.html
{% extends "base.html" %}
<title>{% block title %} Login {% endblock %}</title> 

{% block content %}
<body background="{{ url_for('static', filename='images/983117.jpg')}}">
    <section class="vh-100">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6 text-black">
      
              <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
      
                <form method="POST" style="width: 23rem;">
      
                  <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>
      
                  <div class="form-outline mb-4">
                    <input type="email" id="email" name="email" placeholder="Enter email" class="form-control form-control-lg" />
                  </div>
      
                  <div class="form-outline mb-4">
                    <input type="password" id="password" name="password" placeholder="Enter the Password"  class="form-control form-control-lg" />
                  </div>
      
                  <div class="pt-1 mb-4">
                    <button class="btn btn-info btn-lg btn-block" type="submit">Login</button>
                  </div>
      
                  <p class="small mb-5 pb-lg-2"><a class="text-muted" href="#!">Forgot password?</a></p>
                  <p>Don't have an account? <a href="{{ url_for('auth.register') }}" class="link-info">Register here</a></p>
      
                </form>
      
              </div>
      
            </div>
          </div>
        </div>
      </section>
</body>
  
 {% endblock %}

WebApp/templates/patient_info.html
{% extends "base.html" %}
<title>{% block title %} Home {% endblock %}</title> 

{% block content %}
   <form action="" method="POST">
      <label for="blood-grp">
        <select type="text" placeholder="Select Blood Group">
            <option>A Positive</option>
            <option>A Negative</option>
            <option>A Unknown</option>
            <option>B Positive</option>
            <option>B Negative</option>
            <option>B Unknown</option>
            <option>AB Positive</option>
            <option>AB Negative</option>
            <option>AB Unknown</option>
            <option>O Positive</option>
            <option>O Negative</option>
            <option>O Unknown</option>
            <option>Unknown</option>
        </select>
      </label>
   </form>
{% endblock %}

WebApp/templates/sign_up.html
{% extends "base.html" %}
<title>{% block title %} sign-up {% endblock %}</title> 

{% block content %}
<body background="{{ url_for('static', filename='images/UC_davis_day1-22_telemedicine_hero.jpg')}}">
  <div class="mask d-flex align-items-center h-100 ">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form method="POST">
                <div class="form-outline mb-4">
                    <input type="email" id="email" name="email" class="form-control form-control-lg" placeholder="Enter Your Email Address" />

                  </div>

                <div class="form-outline mb-4">
                  <input type="text" id="firstName" name="firstName" class="form-control form-control-lg" placeholder="Enter Your First Name" />

                </div>

                <div class="form-outline mb-4">
                  <input type="password" id="password1" name="password1" class="form-control form-control-lg" placeholder="Enter Password"/>

                </div>

                <div class="form-outline mb-4">
                    <input type="password" id="password2" name="password2" class="form-control form-control-lg" placeholder="Confirm Password"/>

                </div>

                <div class="form-check d-flex justify-content-center mb-5">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg" />
                  <label class="form-check-label" for="form2Example3g">
                    I agree all statements in <a href="#!" class="text-body"><u>Terms of service</u></a>
                  </label>
                </div>

                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                </div>

                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{{ url_for('auth.login') }}"
                    class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

  {{ form.username }}
  {% if form.username.errors %}
      <p class="error-message">{{ form.username.errors|join:", " }}</p>
  {% endif %}

  {{ form.email }}
  {% if form.email.errors %}
      <p class="error-message">{{ form.email.errors|join:", " }}</p>
  {% endif %}

  {{ form.password1 }}
  {% if form.password1.errors %}
      <p class="error-message">{{ form.password1.errors|join:", " }}</p>
  {% endif %}

  {{ form.password2 }}
  {% if form.password2.errors %}
      <p class="error-message">{{ form.password2.errors|join:", " }}</p>
  {% endif %}

  
 {% endblock %}